name: 'Delete old artifacts'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # every hour

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ github.token }}
          expire-in: 7days # Setting this to 0 will delete all artifacts
